steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/zendesk-integration:$TAG_NAME", "."]
# push image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/zendesk-integration:$TAG_NAME"]
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'zendesk-integration', '--image', 'gcr.io/$PROJECT_ID/zendesk-integration:$TAG_NAME', '--region', 'asia-northeast1','--platform', 'managed', "--allow-unauthenticated"]
images:
- gcr.io/$PROJECT_ID/zendesk-integration:$TAG_NAME
timeout: 2000s
